<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            array('id' => '1','name_ar' => 'أندورا','name_en' => 'Andorra','code' => 'ad'),
            array('id' => '2','name_ar' => 'الإمارات العربية المتحدة','name_en' => 'United Arab Emirates','code' => 'ae'),
            array('id' => '3','name_ar' => 'أفغانستان','name_en' => 'Afghanistan','code' => 'af'),
            array('id' => '4','name_ar' => 'أنتيغوا وبربودا','name_en' => 'Antigua and Barbuda','code' => 'ag'),
            array('id' => '5','name_ar' => 'أنغيلا','name_en' => 'Anguilla','code' => 'ai'),
            array('id' => '6','name_ar' => 'ألبانيا','name_en' => 'Albania','code' => 'al'),
            array('id' => '7','name_ar' => 'أرمينيا','name_en' => 'Armenia','code' => 'am'),
            array('id' => '8','name_ar' => 'جزر الأنتيل الهولندية','name_en' => 'Netherlands Antilles','code' => 'an'),
            array('id' => '9','name_ar' => 'أنغولا','name_en' => 'Angola','code' => 'ao'),
            array('id' => '10','name_ar' => 'الأرجنتين','name_en' => 'Argentina','code' => 'ar'),
            array('id' => '11','name_ar' => 'النمسا','name_en' => 'Austria','code' => 'at'),
            array('id' => '12','name_ar' => 'أستراليا','name_en' => 'Australia','code' => 'au'),
            array('id' => '13','name_ar' => 'أروبا','name_en' => 'Aruba','code' => 'aw'),
            array('id' => '14','name_ar' => 'أذربيجان','name_en' => 'Azerbaijan','code' => 'az'),
            array('id' => '15','name_ar' => 'البوسنة والهرسك','name_en' => 'Bosnia and Herzegovina','code' => 'ba'),
            array('id' => '16','name_ar' => 'بربادوس','name_en' => 'Barbados','code' => 'bb'),
            array('id' => '17','name_ar' => 'بنغلاديش','name_en' => 'Bangladesh','code' => 'bd'),
            array('id' => '18','name_ar' => 'بلجيكا','name_en' => 'Belgium','code' => 'be'),
            array('id' => '19','name_ar' => 'بوركينا فاسو','name_en' => 'Burkina Faso','code' => 'bf'),
            array('id' => '20','name_ar' => 'بلغاريا','name_en' => 'Bulgaria','code' => 'bg'),
            array('id' => '21','name_ar' => 'البحرين','name_en' => 'Bahrain','code' => 'bh'),
            array('id' => '22','name_ar' => 'بوروندي','name_en' => 'Burundi','code' => 'bi'),
            array('id' => '23','name_ar' => 'بنين','name_en' => 'Benin','code' => 'bj'),
            array('id' => '24','name_ar' => 'برمودا','name_en' => 'Bermuda','code' => 'bm'),
            array('id' => '25','name_ar' => 'بروناي دار السلام','name_en' => 'Brunei Darussalam','code' => 'bn'),
            array('id' => '26','name_ar' => 'بوليفيا','name_en' => 'Bolivia','code' => 'bo'),
            array('id' => '27','name_ar' => 'البرازيل','name_en' => 'Brazil','code' => 'br'),
            array('id' => '28','name_ar' => 'الباهاما','name_en' => 'Bahamas','code' => 'bs'),
            array('id' => '29','name_ar' => 'بوتان','name_en' => 'Bhutan','code' => 'bt'),
            array('id' => '30','name_ar' => 'بوتسوانا','name_en' => 'Botswana','code' => 'bw'),
            array('id' => '31','name_ar' => 'روسيا البيضاء','name_en' => 'Belarus','code' => 'by'),
            array('id' => '32','name_ar' => 'بليز','name_en' => 'Belize','code' => 'bz'),
            array('id' => '33','name_ar' => 'كندا','name_en' => 'Canada','code' => 'ca'),
            array('id' => '34','name_ar' => 'جزر كوكوس (كيلينغ)','name_en' => 'Cocos (Keeling) Islands','code' => 'cc'),
            array('id' => '35','name_ar' => 'جمهورية الكونغو الديموقراطية','name_en' => 'Democratic Republic of the Congo','code' => 'cd'),
            array('id' => '36','name_ar' => 'جمهورية افريقيا الوسطى','name_en' => 'Central African Republic','code' => 'cf'),
            array('id' => '37','name_ar' => 'الكونغو','name_en' => 'Congo','code' => 'cg'),
            array('id' => '38','name_ar' => 'سويسرا','name_en' => 'Switzerland','code' => 'ch'),
            array('id' => '39','name_ar' => 'ساحل العاج (ساحل العاج)','name_en' => 'Cote D\'Ivoire (Ivory Coast)','code' => 'ci'),
            array('id' => '40','name_ar' => 'جزر كوك','name_en' => 'Cook Islands','code' => 'ck'),
            array('id' => '41','name_ar' => 'تشيلي','name_en' => 'Chile','code' => 'cl'),
            array('id' => '42','name_ar' => 'الكاميرون','name_en' => 'Cameroon','code' => 'cm'),
            array('id' => '43','name_ar' => 'الصين','name_en' => 'China','code' => 'cn'),
            array('id' => '44','name_ar' => 'كولومبيا','name_en' => 'Colombia','code' => 'co'),
            array('id' => '45','name_ar' => 'كوستا ريكا','name_en' => 'Costa Rica','code' => 'cr'),
            array('id' => '46','name_ar' => 'كوبا','name_en' => 'Cuba','code' => 'cu'),
            array('id' => '47','name_ar' => 'الرأس الأخضر','name_en' => 'Cape Verde','code' => 'cv'),
            array('id' => '48','name_ar' => 'جزيرة الكريسماس','name_en' => 'Christmas Island','code' => 'cx'),
            array('id' => '49','name_ar' => 'قبرص','name_en' => 'Cyprus','code' => 'cy'),
            array('id' => '50','name_ar' => 'جمهورية التشيك','name_en' => 'Czech Republic','code' => 'cz'),
            array('id' => '51','name_ar' => 'ألمانيا','name_en' => 'Germany','code' => 'de'),
            array('id' => '52','name_ar' => 'جيبوتي','name_en' => 'Djibouti','code' => 'dj'),
            array('id' => '53','name_ar' => 'الدنمارك','name_en' => 'Denmark','code' => 'dk'),
            array('id' => '54','name_ar' => 'دومينيكا','name_en' => 'Dominica','code' => 'dm'),
            array('id' => '55','name_ar' => 'جمهورية الدومنيكان','name_en' => 'Dominican Republic','code' => 'do'),
            array('id' => '56','name_ar' => 'الجزائر','name_en' => 'Algeria','code' => 'dz'),
            array('id' => '57','name_ar' => 'الإكوادور','name_en' => 'Ecuador','code' => 'ec'),
            array('id' => '58','name_ar' => 'استونيا','name_en' => 'Estonia','code' => 'ee'),
            array('id' => '59','name_ar' => 'مصر','name_en' => 'Egypt','code' => 'eg'),
            array('id' => '60','name_ar' => 'الصحراء الغربية','name_en' => 'Western Sahara','code' => 'eh'),
            array('id' => '61','name_ar' => 'إريتريا','name_en' => 'Eritrea','code' => 'er'),
            array('id' => '62','name_ar' => 'إسبانيا','name_en' => 'Spain','code' => 'es'),
            array('id' => '63','name_ar' => 'أثيوبيا','name_en' => 'Ethiopia','code' => 'et'),
            array('id' => '64','name_ar' => 'فنلندا','name_en' => 'Finland','code' => 'fi'),
            array('id' => '65','name_ar' => 'فيجي','name_en' => 'Fiji','code' => 'fj'),
            array('id' => '66','name_ar' => 'جزر فوكلاند (مالفيناس)','name_en' => 'Falkland Islands (Malvinas)','code' => 'fk'),
            array('id' => '67','name_ar' => 'ولايات ميكرونيزيا الموحدة','name_en' => 'Federated States of Micronesia','code' => 'fm'),
            array('id' => '68','name_ar' => 'جزر صناعية','name_en' => 'Faroe Islands','code' => 'fo'),
            array('id' => '69','name_ar' => 'فرنسا','name_en' => 'France','code' => 'fr'),
            array('id' => '70','name_ar' => 'الغابون','name_en' => 'Gabon','code' => 'ga'),
            array('id' => '71','name_ar' => 'بريطانيا العظمى (المملكة المتحدة)','name_en' => 'Great Britain (UK)','code' => 'gb'),
            array('id' => '72','name_ar' => 'غرينادا','name_en' => 'Grenada','code' => 'gd'),
            array('id' => '73','name_ar' => 'جورجيا','name_en' => 'Georgia','code' => 'ge'),
            array('id' => '74','name_ar' => 'غيانا الفرنسية','name_en' => 'French Guiana','code' => 'gf'),
            array('id' => '75','name_ar' => 'لا شيء','name_en' => 'NULL','code' => 'gg'),
            array('id' => '76','name_ar' => 'غانا','name_en' => 'Ghana','code' => 'gh'),
            array('id' => '77','name_ar' => 'جبل طارق','name_en' => 'Gibraltar','code' => 'gi'),
            array('id' => '78','name_ar' => 'الأرض الخضراء','name_en' => 'Greenland','code' => 'gl'),
            array('id' => '79','name_ar' => 'غامبيا','name_en' => 'Gambia','code' => 'gm'),
            array('id' => '80','name_ar' => 'غينيا','name_en' => 'Guinea','code' => 'gn'),
            array('id' => '81','name_ar' => 'جوادلوب','name_en' => 'Guadeloupe','code' => 'gp'),
            array('id' => '82','name_ar' => 'غينيا الإستوائية','name_en' => 'Equatorial Guinea','code' => 'gq'),
            array('id' => '83','name_ar' => 'اليونان','name_en' => 'Greece','code' => 'gr'),
            array('id' => '84','name_ar' => 'جورجيا وجزر ساندويتش','name_en' => 'S. Georgia and S. Sandwich Islands','code' => 'gs'),
            array('id' => '85','name_ar' => 'غواتيمالا','name_en' => 'Guatemala','code' => 'gt'),
            array('id' => '86','name_ar' => 'غينيا بيساو','name_en' => 'Guinea-Bissau','code' => 'gw'),
            array('id' => '87','name_ar' => 'غيانا','name_en' => 'Guyana','code' => 'gy'),
            array('id' => '88','name_ar' => 'هونغ كونغ','name_en' => 'Hong Kong','code' => 'hk'),
            array('id' => '89','name_ar' => 'هندوراس','name_en' => 'Honduras','code' => 'hn'),
            array('id' => '90','name_ar' => 'كرواتيا (هرفاتسكا)','name_en' => 'Croatia (Hrvatska)','code' => 'hr'),
            array('id' => '91','name_ar' => 'هايتي','name_en' => 'Haiti','code' => 'ht'),
            array('id' => '92','name_ar' => 'اليونان','name_en' => 'Hungary','code' => 'hu'),
            array('id' => '93','name_ar' => 'أندونيسيا','name_en' => 'Indonesia','code' => 'id'),
            array('id' => '94','name_ar' => 'أيرلندا','name_en' => 'Ireland','code' => 'ie'),
            array('id' => '96','name_ar' => 'الهند','name_en' => 'India','code' => 'in'),
            array('id' => '97','name_ar' => 'العراق','name_en' => 'Iraq','code' => 'iq'),
            array('id' => '98','name_ar' => 'إيران','name_en' => 'Iran','code' => 'ir'),
            array('id' => '99','name_ar' => 'أيسلندا','name_en' => 'Iceland','code' => 'is'),
            array('id' => '100','name_ar' => 'إيطاليا','name_en' => 'Italy','code' => 'it'),
            array('id' => '101','name_ar' => 'جامايكا','name_en' => 'Jamaica','code' => 'jm'),
            array('id' => '102','name_ar' => 'الأردن','name_en' => 'Jordan','code' => 'jo'),
            array('id' => '103','name_ar' => 'اليابان','name_en' => 'Japan','code' => 'jp'),
            array('id' => '104','name_ar' => 'كينيا','name_en' => 'Kenya','code' => 'ke'),
            array('id' => '105','name_ar' => 'قرغيزستان','name_en' => 'Kyrgyzstan','code' => 'kg'),
            array('id' => '106','name_ar' => 'كمبوديا','name_en' => 'Cambodia','code' => 'kh'),
            array('id' => '107','name_ar' => 'كيريباس','name_en' => 'Kiribati','code' => 'ki'),
            array('id' => '108','name_ar' => 'جزر القمر','name_en' => 'Comoros','code' => 'km'),
            array('id' => '109','name_ar' => 'سانت كيتس ونيفيس','name_en' => 'Saint Kitts and Nevis','code' => 'kn'),
            array('id' => '110','name_ar' => 'كوريا الشمالية','name_en' => 'Korea (North)','code' => 'kp'),
            array('id' => '111','name_ar' => 'كوريا، جنوب)','name_en' => 'Korea (South)','code' => 'kr'),
            array('id' => '112','name_ar' => 'الكويت','name_en' => 'Kuwait','code' => 'kw'),
            array('id' => '113','name_ar' => 'جزر كايمان','name_en' => 'Cayman Islands','code' => 'ky'),
            array('id' => '114','name_ar' => 'كازاخستان','name_en' => 'Kazakhstan','code' => 'kz'),
            array('id' => '115','name_ar' => 'لاوس','name_en' => 'Laos','code' => 'la'),
            array('id' => '116','name_ar' => 'لبنان','name_en' => 'Lebanon','code' => 'lb'),
            array('id' => '117','name_ar' => 'القديسة لوسيا','name_en' => 'Saint Lucia','code' => 'lc'),
            array('id' => '118','name_ar' => 'ليختنشتاين','name_en' => 'Liechtenstein','code' => 'li'),
            array('id' => '119','name_ar' => 'سيريلانكا','name_en' => 'Sri Lanka','code' => 'lk'),
            array('id' => '120','name_ar' => 'ليبيريا','name_en' => 'Liberia','code' => 'lr'),
            array('id' => '121','name_ar' => 'ليسوتو','name_en' => 'Lesotho','code' => 'ls'),
            array('id' => '122','name_ar' => 'ليتوانيا','name_en' => 'Lithuania','code' => 'lt'),
            array('id' => '123','name_ar' => 'لوكسمبورغ','name_en' => 'Luxembourg','code' => 'lu'),
            array('id' => '124','name_ar' => 'لاتفيا','name_en' => 'Latvia','code' => 'lv'),
            array('id' => '125','name_ar' => 'ليبيا','name_en' => 'Libya','code' => 'ly'),
            array('id' => '126','name_ar' => 'المغرب','name_en' => 'Morocco','code' => 'ma'),
            array('id' => '127','name_ar' => 'موناكو','name_en' => 'Monaco','code' => 'mc'),
            array('id' => '128','name_ar' => 'مولدوفا','name_en' => 'Moldova','code' => 'md'),
            array('id' => '129','name_ar' => 'مدغشقر','name_en' => 'Madagascar','code' => 'mg'),
            array('id' => '130','name_ar' => 'جزر مارشال','name_en' => 'Marshall Islands','code' => 'mh'),
            array('id' => '131','name_ar' => 'مقدونيا','name_en' => 'Macedonia','code' => 'mk'),
            array('id' => '132','name_ar' => 'مالي','name_en' => 'Mali','code' => 'ml'),
            array('id' => '133','name_ar' => 'ميانمار','name_en' => 'Myanmar','code' => 'mm'),
            array('id' => '134','name_ar' => 'منغوليا','name_en' => 'Mongolia','code' => 'mn'),
            array('id' => '135','name_ar' => 'ماكاو','name_en' => 'Macao','code' => 'mo'),
            array('id' => '136','name_ar' => 'جزر مريانا الشمالية','name_en' => 'Northern Mariana Islands','code' => 'mp'),
            array('id' => '137','name_ar' => 'مارتينيك','name_en' => 'Martinique','code' => 'mq'),
            array('id' => '138','name_ar' => 'موريتانيا','name_en' => 'Mauritania','code' => 'mr'),
            array('id' => '139','name_ar' => 'مونتسيرات','name_en' => 'Montserrat','code' => 'ms'),
            array('id' => '140','name_ar' => 'مالطا','name_en' => 'Malta','code' => 'mt'),
            array('id' => '141','name_ar' => 'موريشيوس','name_en' => 'Mauritius','code' => 'mu'),
            array('id' => '142','name_ar' => 'جزر المالديف','name_en' => 'Maldives','code' => 'mv'),
            array('id' => '143','name_ar' => 'مالاوي','name_en' => 'Malawi','code' => 'mw'),
            array('id' => '144','name_ar' => 'المكسيك','name_en' => 'Mexico','code' => 'mx'),
            array('id' => '145','name_ar' => 'ماليزيا','name_en' => 'Malaysia','code' => 'my'),
            array('id' => '146','name_ar' => 'موزمبيق','name_en' => 'Mozambique','code' => 'mz'),
            array('id' => '147','name_ar' => 'ناميبيا','name_en' => 'Namibia','code' => 'na'),
            array('id' => '148','name_ar' => 'كاليدونيا الجديدة','name_en' => 'New Caledonia','code' => 'nc'),
            array('id' => '149','name_ar' => 'النيجر','name_en' => 'Niger','code' => 'ne'),
            array('id' => '150','name_ar' => 'جزيرة نورفولك','name_en' => 'Norfolk Island','code' => 'nf'),
            array('id' => '151','name_ar' => 'نيجيريا','name_en' => 'Nigeria','code' => 'ng'),
            array('id' => '152','name_ar' => 'نيكاراغوا','name_en' => 'Nicaragua','code' => 'ni'),
            array('id' => '153','name_ar' => 'هولندا','name_en' => 'Netherlands','code' => 'nl'),
            array('id' => '154','name_ar' => 'النرويج','name_en' => 'Norway','code' => 'no'),
            array('id' => '155','name_ar' => 'نيبال','name_en' => 'Nepal','code' => 'np'),
            array('id' => '156','name_ar' => 'ناورو','name_en' => 'Nauru','code' => 'nr'),
            array('id' => '157','name_ar' => 'نيوي','name_en' => 'Niue','code' => 'nu'),
            array('id' => '158','name_ar' => 'نيوزيلندا (اوتياروا)','name_en' => 'New Zealand (Aotearoa)','code' => 'nz'),
            array('id' => '159','name_ar' => 'سلطنة عمان','name_en' => 'Oman','code' => 'om'),
            array('id' => '160','name_ar' => 'بناما','name_en' => 'Panama','code' => 'pa'),
            array('id' => '161','name_ar' => 'بيرو','name_en' => 'Peru','code' => 'pe'),
            array('id' => '162','name_ar' => 'بولينيزيا الفرنسية','name_en' => 'French Polynesia','code' => 'pf'),
            array('id' => '163','name_ar' => 'بابوا غينيا الجديدة','name_en' => 'Papua New Guinea','code' => 'pg'),
            array('id' => '164','name_ar' => 'الفلبين','name_en' => 'Philippines','code' => 'ph'),
            array('id' => '165','name_ar' => 'باكستان','name_en' => 'Pakistan','code' => 'pk'),
            array('id' => '166','name_ar' => 'بولندا','name_en' => 'Poland','code' => 'pl'),
            array('id' => '167','name_ar' => 'سانت بيير وميكلون','name_en' => 'Saint Pierre and Miquelon','code' => 'pm'),
            array('id' => '168','name_ar' => 'بيتكيرن','name_en' => 'Pitcairn','code' => 'pn'),
            array('id' => '169','name_ar' => 'الأراضي الفلسطينية','name_en' => 'Palestinian Territory','code' => 'ps'),
            array('id' => '170','name_ar' => 'البرتغال','name_en' => 'Portugal','code' => 'pt'),
            array('id' => '171','name_ar' => 'بالاو','name_en' => 'Palau','code' => 'pw'),
            array('id' => '172','name_ar' => 'باراغواي','name_en' => 'Paraguay','code' => 'py'),
            array('id' => '173','name_ar' => 'دولة قطر','name_en' => 'Qatar','code' => 'qa'),
            array('id' => '174','name_ar' => 'جمع شمل','name_en' => 'Reunion','code' => 're'),
            array('id' => '175','name_ar' => 'رومانيا','name_en' => 'Romania','code' => 'ro'),
            array('id' => '176','name_ar' => 'الاتحاد الروسي','name_en' => 'Russian Federation','code' => 'ru'),
            array('id' => '177','name_ar' => 'رواندا','name_en' => 'Rwanda','code' => 'rw'),
            array('id' => '178','name_ar' => 'المملكة العربية السعودية','name_en' => 'Saudi Arabia','code' => 'sa'),
            array('id' => '179','name_ar' => 'جزر سليمان','name_en' => 'Solomon Islands','code' => 'sb'),
            array('id' => '180','name_ar' => 'سيشيل','name_en' => 'Seychelles','code' => 'sc'),
            array('id' => '181','name_ar' => 'سودان','name_en' => 'Sudan','code' => 'sd'),
            array('id' => '182','name_ar' => 'السويد','name_en' => 'Sweden','code' => 'se'),
            array('id' => '183','name_ar' => 'سنغافورة','name_en' => 'Singapore','code' => 'sg'),
            array('id' => '184','name_ar' => 'سانت هيلانة','name_en' => 'Saint Helena','code' => 'sh'),
            array('id' => '185','name_ar' => 'سلوفينيا','name_en' => 'Slovenia','code' => 'si'),
            array('id' => '186','name_ar' => 'سفالبارد وجان مايان','name_en' => 'Svalbard and Jan Mayen','code' => 'sj'),
            array('id' => '187','name_ar' => 'سلوفاكيا','name_en' => 'Slovakia','code' => 'sk'),
            array('id' => '188','name_ar' => 'سيرا ليون','name_en' => 'Sierra Leone','code' => 'sl'),
            array('id' => '189','name_ar' => 'سان مارينو','name_en' => 'San Marino','code' => 'sm'),
            array('id' => '190','name_ar' => 'السنغال','name_en' => 'Senegal','code' => 'sn'),
            array('id' => '191','name_ar' => 'الصومال','name_en' => 'Somalia','code' => 'so'),
            array('id' => '192','name_ar' => 'سورينام','name_en' => 'Suriname','code' => 'sr'),
            array('id' => '193','name_ar' => 'ساو تومي وبرنسيبي','name_en' => 'Sao Tome and Principe','code' => 'st'),
            array('id' => '194','name_ar' => 'السلفادور','name_en' => 'El Salvador','code' => 'sv'),
            array('id' => '195','name_ar' => 'سوريا','name_en' => 'Syria','code' => 'sy'),
            array('id' => '196','name_ar' => 'سوازيلاند','name_en' => 'Swaziland','code' => 'sz'),
            array('id' => '197','name_ar' => 'جزر تركس وكايكوس','name_en' => 'Turks and Caicos Islands','code' => 'tc'),
            array('id' => '198','name_ar' => 'تشاد','name_en' => 'Chad','code' => 'td'),
            array('id' => '199','name_ar' => 'المناطق الجنوبية لفرنسا','name_en' => 'French Southern Territories','code' => 'tf'),
            array('id' => '200','name_ar' => 'ليذهب','name_en' => 'Togo','code' => 'tg'),
            array('id' => '201','name_ar' => 'تايلاند','name_en' => 'Thailand','code' => 'th'),
            array('id' => '202','name_ar' => 'طاجيكستان','name_en' => 'Tajikistan','code' => 'tj'),
            array('id' => '203','name_ar' => 'توكيلاو','name_en' => 'Tokelau','code' => 'tk'),
            array('id' => '204','name_ar' => 'تركمانستان','name_en' => 'Turkmenistan','code' => 'tm'),
            array('id' => '205','name_ar' => 'تونس','name_en' => 'Tunisia','code' => 'tn'),
            array('id' => '206','name_ar' => 'تونغا','name_en' => 'Tonga','code' => 'to'),
            array('id' => '207','name_ar' => 'ديك رومي','name_en' => 'Turkey','code' => 'tr'),
            array('id' => '208','name_ar' => 'ترينداد وتوباغو','name_en' => 'Trinidad and Tobago','code' => 'tt'),
            array('id' => '209','name_ar' => 'توفالو','name_en' => 'Tuvalu','code' => 'tv'),
            array('id' => '210','name_ar' => 'تايوان','name_en' => 'Taiwan','code' => 'tw'),
            array('id' => '211','name_ar' => 'تنزانيا','name_en' => 'Tanzania','code' => 'tz'),
            array('id' => '212','name_ar' => 'أوكرانيا','name_en' => 'Ukraine','code' => 'ua'),
            array('id' => '213','name_ar' => 'أوغندا','name_en' => 'Uganda','code' => 'ug'),
            array('id' => '214','name_ar' => 'أوروغواي','name_en' => 'Uruguay','code' => 'uy'),
            array('id' => '215','name_ar' => 'أوزبكستان','name_en' => 'Uzbekistan','code' => 'uz'),
            array('id' => '216','name_ar' => 'سانت فنسنت وجزر غرينادين','name_en' => 'Saint Vincent and the Grenadines','code' => 'vc'),
            array('id' => '217','name_ar' => 'فنزويلا','name_en' => 'Venezuela','code' => 've'),
            array('id' => '218','name_ar' => 'جزر العذراء البريطانية)','name_en' => 'Virgin Islands (British)','code' => 'vg'),
            array('id' => '219','name_ar' => 'جزر فيرجن (الولايات المتحدة)','name_en' => 'Virgin Islands (U.S.)','code' => 'vi'),
            array('id' => '220','name_ar' => 'فيتنام','name_en' => 'Viet Nam','code' => 'vn'),
            array('id' => '221','name_ar' => 'فانواتو','name_en' => 'Vanuatu','code' => 'vu'),
            array('id' => '222','name_ar' => 'واليس وفوتونا','name_en' => 'Wallis and Futuna','code' => 'wf'),
            array('id' => '223','name_ar' => 'ساموا','name_en' => 'Samoa','code' => 'ws'),
            array('id' => '224','name_ar' => 'اليمن','name_en' => 'Yemen','code' => 'ye'),
            array('id' => '225','name_ar' => 'مايوت','name_en' => 'Mayotte','code' => 'yt'),
            array('id' => '226','name_ar' => 'جنوب أفريقيا','name_en' => 'South Africa','code' => 'za'),
            array('id' => '227','name_ar' => 'زامبيا','name_en' => 'Zambia','code' => 'zm'),
            array('id' => '228','name_ar' => 'زائير (سابقة)','name_en' => 'Zaire (former)','code' => 'zr'),
            array('id' => '229','name_ar' => 'زيمبابوي','name_en' => 'Zimbabwe','code' => 'zw'),
            array('id' => '230','name_ar' => 'الولايات المتحدة','name_en' => 'United States of America','code' => 'us'),
            array('id' => '231','name_ar' => 'غير معروف','name_en' => 'unknown','code' => 'null')
        ];


        \DB::table('countries')->insert($countries);
    }
}
